sonar.projectKey=husky-poc
sonar.projectName=Husky POC
sonar.projectVersion=0.0.0
sonar.host.url=http://localhost:9002
sonar.token=squ_d61aeb29c801d0e724b94012bcab25e71b852043
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.jsx,**/*.test.js
sonar.sourceEncoding=UTF-8
sonar.coverage.exclusions=**/*.test.js,**/*.test.jsx,**/node_modules/**
sonar.scanner.skipJreProvisioning=true
sonar.javascript.lcov.reportPaths=coverage/lcov.info
